<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RanksAndDesignationsSeeder extends Seeder
{
    public function run(): void
    {
        $now = now();

        $aliases = fn (array $items) => json_encode($items, JSON_UNESCAPED_UNICODE);

        $ranks = [
            [
                'code' => 'CONSTABLE',
                'name_en' => 'Constable',
                'short_name' => 'Constable',
                'name_hi' => 'आरक्षी / सिपाही',
                'rank_order' => 10,
                'cadre_type' => 'SUBORDINATE',
                'is_gazetted' => false,
                'aliases' => $aliases(['Sipahi', 'Police Constable', 'आरक्षी', 'सिपाही']),
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'code' => 'HEAD_CONSTABLE',
                'name_en' => 'Head Constable',
                'short_name' => 'HC',
                'name_hi' => 'मुख्य आरक्षी',
                'rank_order' => 20,
                'cadre_type' => 'SUBORDINATE',
                'is_gazetted' => false,
                'aliases' => $aliases(['HC', 'Head Constable', 'मुख्य आरक्षी']),
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'code' => 'ASI',
                'name_en' => 'Assistant Sub-Inspector',
                'short_name' => 'ASI',
                'name_hi' => 'सहायक उप निरीक्षक',
                'rank_order' => 30,
                'cadre_type' => 'SUBORDINATE',
                'is_gazetted' => false,
                'aliases' => $aliases(['Assistant SI', 'Assistant Sub Inspector', 'ASI']),
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'code' => 'SI',
                'name_en' => 'Sub-Inspector',
                'short_name' => 'SI',
                'name_hi' => 'उप निरीक्षक / दरोगा',
                'rank_order' => 40,
                'cadre_type' => 'SUBORDINATE',
                'is_gazetted' => false,
                'aliases' => $aliases(['Sub Inspector', 'SI', 'Daroga', 'दरोगा']),
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'code' => 'INSPECTOR',
                'name_en' => 'Inspector',
                'short_name' => 'Inspector',
                'name_hi' => 'निरीक्षक',
                'rank_order' => 50,
                'cadre_type' => 'SUBORDINATE',
                'is_gazetted' => false,
                'aliases' => $aliases(['Police Inspector', 'Inspector']),
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'code' => 'DSP',
                'name_en' => 'Deputy Superintendent of Police',
                'short_name' => 'DySP / DSP',
                'name_hi' => 'पुलिस उपाधीक्षक',
                'rank_order' => 60,
                'cadre_type' => 'PPS',
                'is_gazetted' => true,
                'aliases' => $aliases(['DSP', 'DySP', 'Circle Officer', 'CO', 'पुलिस उपाधीक्षक']),
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'code' => 'ASP',
                'name_en' => 'Assistant Superintendent of Police',
                'short_name' => 'ASP',
                'name_hi' => 'सहायक पुलिस अधीक्षक',
                'rank_order' => 70,
                'cadre_type' => 'IPS',
                'is_gazetted' => true,
                'aliases' => $aliases(['Assistant SP', 'ASP']),
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'code' => 'ADDL_SP',
                'name_en' => 'Additional Superintendent of Police',
                'short_name' => 'Addl. SP',
                'name_hi' => 'अपर पुलिस अधीक्षक',
                'rank_order' => 80,
                'cadre_type' => 'PPS_OR_IPS',
                'is_gazetted' => true,
                'aliases' => $aliases(['Additional SP', 'Addl SP', 'Addl. SP']),
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'code' => 'SP',
                'name_en' => 'Superintendent of Police',
                'short_name' => 'SP',
                'name_hi' => 'पुलिस अधीक्षक',
                'rank_order' => 90,
                'cadre_type' => 'IPS_OR_PPS',
                'is_gazetted' => true,
                'aliases' => $aliases(['SP', 'Superintendent Police']),
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'code' => 'SSP',
                'name_en' => 'Senior Superintendent of Police',
                'short_name' => 'SSP',
                'name_hi' => 'वरिष्ठ पुलिस अधीक्षक',
                'rank_order' => 100,
                'cadre_type' => 'IPS',
                'is_gazetted' => true,
                'aliases' => $aliases(['SSP', 'Senior SP']),
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'code' => 'DIG',
                'name_en' => 'Deputy Inspector General of Police',
                'short_name' => 'DIG',
                'name_hi' => 'पुलिस उप महानिरीक्षक',
                'rank_order' => 110,
                'cadre_type' => 'IPS',
                'is_gazetted' => true,
                'aliases' => $aliases(['DIG', 'Deputy Inspector General']),
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'code' => 'IG',
                'name_en' => 'Inspector General of Police',
                'short_name' => 'IG',
                'name_hi' => 'पुलिस महानिरीक्षक',
                'rank_order' => 120,
                'cadre_type' => 'IPS',
                'is_gazetted' => true,
                'aliases' => $aliases(['IG', 'IGP', 'Inspector General']),
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'code' => 'ADG',
                'name_en' => 'Additional Director General of Police',
                'short_name' => 'ADG',
                'name_hi' => 'अपर पुलिस महानिदेशक',
                'rank_order' => 130,
                'cadre_type' => 'IPS',
                'is_gazetted' => true,
                'aliases' => $aliases(['ADG', 'ADGP', 'Additional DGP']),
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'code' => 'DG',
                'name_en' => 'Director General of Police',
                'short_name' => 'DG / DGP',
                'name_hi' => 'पुलिस महानिदेशक',
                'rank_order' => 140,
                'cadre_type' => 'IPS',
                'is_gazetted' => true,
                'aliases' => $aliases(['DG', 'DGP', 'Director General of Police']),
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        DB::table('ranks')->upsert(
            $ranks,
            ['code'],
            [
                'name_en',
                'short_name',
                'name_hi',
                'rank_order',
                'cadre_type',
                'is_gazetted',
                'aliases',
                'is_active',
                'updated_at',
            ]
        );

        $designations = [
            [
                'code' => 'DGP_UP',
                'name_en' => 'Director General of Police, Uttar Pradesh',
                'short_name' => 'DGP',
                'name_hi' => 'पुलिस महानिदेशक, उत्तर प्रदेश',
                'designation_order' => 10,
                'mapped_rank_code' => 'DG',
                'designation_type' => 'STATE_HEAD',
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'code' => 'CP',
                'name_en' => 'Commissioner of Police',
                'short_name' => 'CP',
                'name_hi' => 'पुलिस आयुक्त',
                'designation_order' => 20,
                'mapped_rank_code' => null,
                'designation_type' => 'COMMISSIONERATE',
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'code' => 'JCP',
                'name_en' => 'Joint Commissioner of Police',
                'short_name' => 'JCP',
                'name_hi' => 'संयुक्त पुलिस आयुक्त',
                'designation_order' => 30,
                'mapped_rank_code' => null,
                'designation_type' => 'COMMISSIONERATE',
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'code' => 'ADDL_CP',
                'name_en' => 'Additional Commissioner of Police',
                'short_name' => 'Addl. CP',
                'name_hi' => 'अपर पुलिस आयुक्त',
                'designation_order' => 40,
                'mapped_rank_code' => null,
                'designation_type' => 'COMMISSIONERATE',
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'code' => 'DCP',
                'name_en' => 'Deputy Commissioner of Police',
                'short_name' => 'DCP',
                'name_hi' => 'पुलिस उपायुक्त',
                'designation_order' => 50,
                'mapped_rank_code' => 'SP',
                'designation_type' => 'COMMISSIONERATE',
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'code' => 'ADCP',
                'name_en' => 'Additional Deputy Commissioner of Police',
                'short_name' => 'ADCP',
                'name_hi' => 'अपर पुलिस उपायुक्त',
                'designation_order' => 60,
                'mapped_rank_code' => 'ADDL_SP',
                'designation_type' => 'COMMISSIONERATE',
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'code' => 'ACP',
                'name_en' => 'Assistant Commissioner of Police',
                'short_name' => 'ACP',
                'name_hi' => 'सहायक पुलिस आयुक्त',
                'designation_order' => 70,
                'mapped_rank_code' => 'DSP',
                'designation_type' => 'COMMISSIONERATE',
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'code' => 'CO',
                'name_en' => 'Circle Officer',
                'short_name' => 'CO',
                'name_hi' => 'क्षेत्राधिकारी',
                'designation_order' => 80,
                'mapped_rank_code' => 'DSP',
                'designation_type' => 'DISTRICT_POLICING',
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'code' => 'SHO',
                'name_en' => 'Station House Officer',
                'short_name' => 'SHO',
                'name_hi' => 'थाना प्रभारी',
                'designation_order' => 90,
                'mapped_rank_code' => null,
                'designation_type' => 'POLICE_STATION',
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'code' => 'SO',
                'name_en' => 'Station Officer',
                'short_name' => 'SO',
                'name_hi' => 'थानाध्यक्ष',
                'designation_order' => 100,
                'mapped_rank_code' => null,
                'designation_type' => 'POLICE_STATION',
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'code' => 'CHOWKI_INCHARGE',
                'name_en' => 'Police Outpost Incharge',
                'short_name' => 'Chowki Incharge',
                'name_hi' => 'चौकी प्रभारी',
                'designation_order' => 110,
                'mapped_rank_code' => null,
                'designation_type' => 'POLICE_OUTPOST',
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        DB::table('designations')->upsert(
            $designations,
            ['code'],
            [
                'name_en',
                'short_name',
                'name_hi',
                'designation_order',
                'mapped_rank_code',
                'designation_type',
                'is_active',
                'updated_at',
            ]
        );
    }
}
