<?php

use App\Http\Controllers\AchievementBenefitController;
use App\Http\Controllers\Api\V1\MemberAuditLogController;
use App\Http\Controllers\CoachAliasController;
use App\Http\Controllers\CoachCertificationController;
use App\Http\Controllers\CoachController;
use App\Http\Controllers\CoachExportController;
use App\Http\Controllers\CoachPhotoController;
use App\Http\Controllers\CoachProfileTabController;
use App\Http\Controllers\CoachPromotionController;
use App\Http\Controllers\CoachSportController;
use App\Http\Controllers\CoachStatusController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\EventController;
use App\Http\Controllers\EventParticipantController;
use App\Http\Controllers\ExternalCoach\AthleteController as ExternalCoachAthleteController;
use App\Http\Controllers\ExternalCoach\Auth\ExternalCoachLoginController;
use App\Http\Controllers\ExternalCoach\DashboardController as ExternalCoachDashboardController;
use App\Http\Controllers\ExternalCoach\ExternalCoachPerformanceUpdateController;
use App\Http\Controllers\ExternalCoach\ExternalTrainingAttendanceController;
use App\Http\Controllers\ExternalCoachController;
use App\Http\Controllers\ExternalCoachingAssignmentController;
use App\Http\Controllers\ExternalCoachPerformanceUpdateController as AdminExternalCoachPerformanceUpdateController;
use App\Http\Controllers\ExternalTrainingAttendanceController as AdminExternalTrainingAttendanceController;
use App\Http\Controllers\InchargeAchievementController;
use App\Http\Controllers\InchargeController;
use App\Http\Controllers\InchargePhotoController;
use App\Http\Controllers\InchargeProfileTabController;
use App\Http\Controllers\InchargeSpecialAchievementController;
use App\Http\Controllers\LocaleController;
use App\Http\Controllers\MedalsExportController;
use App\Http\Controllers\MedalsReportExportController;
use App\Http\Controllers\MediaFileController;
use App\Http\Controllers\MemberAchievementContextController;
use App\Http\Controllers\MemberAliasController;
use App\Http\Controllers\MemberController;
use App\Http\Controllers\MemberExportController;
use App\Http\Controllers\MemberImportController;
use App\Http\Controllers\MemberPhotoController;
use App\Http\Controllers\MemberProfileTabController;
use App\Http\Controllers\MemberPromotionController;
use App\Http\Controllers\MemberSpecialAchievementController;
use App\Http\Controllers\MemberStatusController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\ReportsMedalsController;
use App\Http\Controllers\SportsCalendarController;
use App\Http\Controllers\TeamCloneController;
use App\Http\Controllers\TeamCoachController;
use App\Http\Controllers\TeamController;
use App\Http\Controllers\TeamExportController;
use App\Http\Controllers\TeamInchargeController;
use App\Http\Controllers\TeamMemberController;
use App\Http\Controllers\TeamProfileTabController;
use App\Http\Controllers\TeamSessionStatusController;
use App\Http\Controllers\TournamentController;
use App\Http\Controllers\TournamentExportController;
use App\Http\Controllers\TournamentProfileTabController;
use App\Http\Controllers\TrainingVenueController;
use Illuminate\Support\Facades\Route;

Route::patch('/locale', [LocaleController::class, 'update'])->name('locale.update');

Route::inertia('/', 'welcome')->name('home');

Route::prefix('external-coach')->name('external-coach.')->group(function (): void {
    Route::middleware('guest:external_coach')->group(function (): void {
        Route::get('login', [ExternalCoachLoginController::class, 'create'])->name('login');
        Route::post('login', [ExternalCoachLoginController::class, 'store'])->name('login.store');
    });

    Route::middleware(['auth:external_coach', 'external.coach.active'])->group(function (): void {
        Route::get('dashboard', ExternalCoachDashboardController::class)->name('dashboard');
        Route::get('athletes/{member}', [ExternalCoachAthleteController::class, 'show'])->name('athletes.show');
        Route::get('athletes/{member}/attendance', [ExternalCoachAthleteController::class, 'attendance'])->name('athletes.attendance');
        Route::get('athletes/{member}/performance', [ExternalCoachAthleteController::class, 'performance'])->name('athletes.performance');
        Route::get('attendance', [ExternalTrainingAttendanceController::class, 'index'])->name('attendance.index');
        Route::post('attendance', [ExternalTrainingAttendanceController::class, 'store'])->name('attendance.store');
        Route::get('performance', [ExternalCoachPerformanceUpdateController::class, 'index'])->name('performance.index');
        Route::post('performance', [ExternalCoachPerformanceUpdateController::class, 'store'])->name('performance.store');
        Route::post('logout', [ExternalCoachLoginController::class, 'destroy'])->name('logout');
    });
});

Route::middleware(['auth', 'verified'])->group(function () {
    Route::get('dashboard', DashboardController::class)->name('dashboard');
    Route::get('external-coaches/{externalCoach}/assignments', [ExternalCoachController::class, 'assignments'])->name('external-coaches.assignments');
    Route::get('external-coaches/{externalCoach}/members/{member}/assignments', [ExternalCoachController::class, 'playerAssignments'])->name('external-coaches.player-assignments');
    Route::resource('external-coaches', ExternalCoachController::class);
    Route::resource('training-venues', TrainingVenueController::class);
    Route::get('external-coaching-assignments/{external_coaching_assignment}/permission-document', [ExternalCoachingAssignmentController::class, 'permissionDocument'])->name('external-coaching-assignments.permission-document');
    Route::get('external-coaching-assignments/{external_coaching_assignment}/permission-document/preview', [ExternalCoachingAssignmentController::class, 'previewPermissionDocument'])->name('external-coaching-assignments.permission-document.preview');
    Route::resource('external-coaching-assignments', ExternalCoachingAssignmentController::class);
    Route::get('external-training-attendances/export', [AdminExternalTrainingAttendanceController::class, 'export'])->name('external-training-attendances.export');
    Route::get('external-training-attendances/{external_training_attendance}/photo', [AdminExternalTrainingAttendanceController::class, 'photo'])->name('external-training-attendances.photo');
    Route::get('external-training-attendances/{external_training_attendance}/photo/preview', [AdminExternalTrainingAttendanceController::class, 'previewPhoto'])->name('external-training-attendances.photo.preview');
    Route::patch('external-training-attendances/{external_training_attendance}/review', [AdminExternalTrainingAttendanceController::class, 'review'])->name('external-training-attendances.review');
    Route::resource('external-training-attendances', AdminExternalTrainingAttendanceController::class)->only(['index', 'show']);
    Route::get('external-coach-performance-updates', [AdminExternalCoachPerformanceUpdateController::class, 'index'])->name('external-coach-performance-updates.index');
    Route::get('external-coach-performance-updates/{performance_update}', [AdminExternalCoachPerformanceUpdateController::class, 'show'])->name('external-coach-performance-updates.show');
    Route::patch('external-coach-performance-updates/{performance_update}/review', [AdminExternalCoachPerformanceUpdateController::class, 'review'])->name('external-coach-performance-updates.review');
    Route::get('members/export', [MemberExportController::class, 'index'])->name('members.export');
    Route::get('members/print', [MemberExportController::class, 'print'])->name('members.print');
    Route::get('members/import/template', [MemberImportController::class, 'template'])->name('members.import.template');
    Route::post('members/import', [MemberImportController::class, 'store'])->name('members.import.store');
    Route::get('imports/{import}/errors', [MemberImportController::class, 'errors'])->name('imports.errors');
    Route::resource('members', MemberController::class);
    Route::get('members/{member}/teams', [MemberProfileTabController::class, 'teams'])->name('members.teams');
    Route::get('members/{member}/events', [MemberProfileTabController::class, 'events'])->name('members.events');
    Route::get('members/{member}/performance', [MemberProfileTabController::class, 'performance'])->name('members.performance');
    Route::get('members/{member}/external-coaching', [MemberProfileTabController::class, 'externalCoaching'])->name('members.external-coaching');
    Route::get('members/{member}/special-achievements', [MemberProfileTabController::class, 'specialAchievements'])->name('members.special-achievements');
    Route::get('members/{member}/promotions', [MemberProfileTabController::class, 'promotions'])->name('members.promotions');
    Route::get('members/{member}/changelog', [MemberProfileTabController::class, 'changelog'])->name('members.changelog');
    Route::get('members/{member}/media', [MemberProfileTabController::class, 'media'])->name('members.media');
    Route::get('members/{member}/status', [MemberProfileTabController::class, 'status'])->name('members.status');
    Route::get('members/{member}/preview', [MemberController::class, 'preview'])->name('members.preview');
    Route::get('members/{member}/export', [MemberExportController::class, 'show'])->name('members.export.show');
    Route::get('coaches/export', [CoachExportController::class, 'index'])->name('coaches.export');
    Route::get('coaches/print', [CoachController::class, 'print'])->name('coaches.print');
    Route::resource('coaches', CoachController::class);
    Route::get('coaches/{coach}/assignments', [CoachProfileTabController::class, 'assignments'])->name('coaches.assignments');
    Route::get('coaches/{coach}/sports', [CoachProfileTabController::class, 'sports'])->name('coaches.sports');
    Route::get('coaches/{coach}/certifications', [CoachProfileTabController::class, 'certifications'])->name('coaches.certifications');
    Route::get('coaches/{coach}/achievements', [CoachProfileTabController::class, 'achievements'])->name('coaches.achievements');
    Route::get('coaches/{coach}/promotions', [CoachProfileTabController::class, 'promotions'])->name('coaches.promotions');
    Route::get('coaches/{coach}/media', [CoachProfileTabController::class, 'media'])->name('coaches.media');
    Route::get('coaches/{coach}/aliases', [CoachProfileTabController::class, 'aliases'])->name('coaches.aliases');
    Route::get('coaches/{coach}/changelog', [CoachProfileTabController::class, 'changelog'])->name('coaches.changelog');
    Route::get('coaches/{coach}/status', [CoachProfileTabController::class, 'status'])->name('coaches.status');
    Route::get('coaches/{coach}/preview', [CoachController::class, 'preview'])->name('coaches.preview');
    Route::get('coaches/{coach}/export', [CoachExportController::class, 'show'])->name('coaches.export.show');
    Route::post('coaches/{coach}/status', [CoachStatusController::class, 'store'])->name('coaches.status.store');
    Route::post('coaches/{coach}/sports', [CoachSportController::class, 'store'])->name('coaches.sports.store');
    Route::delete('coaches/{coach}/sports/{coachSport}', [CoachSportController::class, 'destroy'])->name('coaches.sports.destroy');
    Route::post('coaches/{coach}/certifications', [CoachCertificationController::class, 'store'])->name('coaches.certifications.store');
    Route::delete('coaches/{coach}/certifications/{certification}', [CoachCertificationController::class, 'destroy'])->name('coaches.certifications.destroy');
    Route::get('coaches/{coach}/certifications/{certification}/attachment', [CoachCertificationController::class, 'downloadAttachment'])->name('coaches.certifications.attachment.download');
    Route::get('coaches/{coach}/certifications/{certification}/attachment/preview', [CoachCertificationController::class, 'previewAttachment'])->name('coaches.certifications.attachment.preview');
    Route::post('coaches/{coach}/promotions', [CoachPromotionController::class, 'store'])->name('coaches.promotions.store');
    Route::patch('coaches/{coach}/promotions/{promotion}', [CoachPromotionController::class, 'update'])->name('coaches.promotions.update');
    Route::delete('coaches/{coach}/promotions/{promotion}', [CoachPromotionController::class, 'destroy'])->name('coaches.promotions.destroy');
    Route::post('coaches/{coach}/aliases', [CoachAliasController::class, 'store'])->name('coaches.aliases.store');
    Route::delete('coaches/{coach}/aliases/{alias}', [CoachAliasController::class, 'destroy'])->name('coaches.aliases.destroy');
    Route::post('coaches/{coach}/photo', [CoachPhotoController::class, 'store'])->name('coaches.photo.store');
    Route::delete('coaches/{coach}/photo', [CoachPhotoController::class, 'destroy'])->name('coaches.photo.destroy');
    Route::resource('incharges', InchargeController::class);
    Route::get('incharges/{incharge}/preview', [InchargeController::class, 'preview'])->name('incharges.preview');
    Route::get('incharges/{incharge}/profile', [InchargeProfileTabController::class, 'profile'])->name('incharges.profile');
    Route::get('incharges/{incharge}/achievements', [InchargeProfileTabController::class, 'achievements'])->name('incharges.achievements');
    Route::post('incharges/{incharge}/achievements', [InchargeAchievementController::class, 'store'])->name('incharges.achievements.store');
    Route::patch('incharges/{incharge}/achievements/{achievement}', [InchargeAchievementController::class, 'update'])->name('incharges.achievements.update');
    Route::delete('incharges/{incharge}/achievements/{achievement}', [InchargeAchievementController::class, 'destroy'])->name('incharges.achievements.destroy');
    Route::get('incharges/{incharge}/special-achievements', [InchargeProfileTabController::class, 'specialAchievements'])->name('incharges.special-achievements');
    Route::post('incharges/{incharge}/special-achievements', [InchargeSpecialAchievementController::class, 'store'])->name('incharges.special-achievements.store');
    Route::patch('incharges/{incharge}/special-achievements/{specialAchievement}', [InchargeSpecialAchievementController::class, 'update'])->name('incharges.special-achievements.update');
    Route::delete('incharges/{incharge}/special-achievements/{specialAchievement}', [InchargeSpecialAchievementController::class, 'destroy'])->name('incharges.special-achievements.destroy');
    Route::get('incharges/{incharge}/special-achievements/{specialAchievement}/order-document', [InchargeSpecialAchievementController::class, 'orderDocument'])->name('incharges.special-achievements.order-document');
    Route::get('incharges/{incharge}/special-achievements/{specialAchievement}/order-document/preview', [InchargeSpecialAchievementController::class, 'previewOrderDocument'])->name('incharges.special-achievements.order-document.preview');
    Route::get('incharges/{incharge}/teams', [InchargeProfileTabController::class, 'teams'])->name('incharges.teams');
    Route::get('incharges/{incharge}/changelog', [InchargeProfileTabController::class, 'changelog'])->name('incharges.changelog');
    Route::post('incharges/{incharge}/photo', [InchargePhotoController::class, 'store'])->name('incharges.photo.store');
    Route::delete('incharges/{incharge}/photo', [InchargePhotoController::class, 'destroy'])->name('incharges.photo.destroy');
    Route::get('teams/export', [TeamExportController::class, 'index'])->name('teams.export');
    Route::get('teams/print', [TeamController::class, 'printRoster'])->name('teams.print');
    Route::get('teams/{team}/players', [TeamProfileTabController::class, 'players'])->name('teams.players');
    Route::get('teams/{team}/coaches', [TeamProfileTabController::class, 'coaches'])->name('teams.coaches');
    Route::get('teams/{team}/incharge', [TeamProfileTabController::class, 'incharge'])->name('teams.incharge');
    Route::get('teams/{team}/changelog', [TeamProfileTabController::class, 'changelog'])->name('teams.changelog');
    Route::resource('teams', TeamController::class)->except(['destroy']);
    Route::get('tournaments/export', [TournamentExportController::class, 'index'])->name('tournaments.export');
    Route::get('tournaments/{tournament}/events/report', [TournamentExportController::class, 'eventsReport'])->name('tournaments.events.report');
    Route::get('tournaments/{tournament}/events/export', [TournamentExportController::class, 'eventsExport'])->name('tournaments.events.export');
    Route::get('tournaments/{tournament}/events', [TournamentProfileTabController::class, 'events'])->name('tournaments.events');
    Route::resource('tournaments', TournamentController::class);
    Route::get('sports-calendars/{sports_calendar}/report', [SportsCalendarController::class, 'report'])->name('sports-calendars.report');
    Route::get('sports-calendars/{sports_calendar}/report/preview', [SportsCalendarController::class, 'previewReport'])->name('sports-calendars.report.preview');
    Route::resource('sports-calendars', SportsCalendarController::class)->except(['destroy', 'show']);
    Route::get('reports', [ReportController::class, 'index'])->name('reports.index');
    Route::get('reports/medals', ReportsMedalsController::class)->name('reports.medals');
    Route::get('reports/medals/detail', [ReportsMedalsController::class, 'detail'])->name('reports.medals.detail');
    Route::get('reports/medals/print', [ReportsMedalsController::class, 'print'])->name('reports.medals.print');
    Route::get('reports/medals/export', MedalsExportController::class)->name('reports.medals.export');
    Route::post('reports/medals/exports', [MedalsReportExportController::class, 'store'])->name('reports.medals.exports.store');
    Route::get('reports/medals/exports/{export}', [MedalsReportExportController::class, 'show'])->name('reports.medals.exports.show');
    Route::get('reports/medals/exports/{export}/download', [MedalsReportExportController::class, 'download'])->name('reports.medals.exports.download');
    Route::get('reports/{key}/members/{member}/performance', [ReportController::class, 'memberPerformanceDetail'])->name('reports.member-performance-detail');
    Route::get('reports/{key}/drilldown', [ReportController::class, 'playerPerformanceDrilldown'])->name('reports.player-performance-drilldown');
    Route::get('reports/{key}/export', [ReportController::class, 'export'])->name('reports.export');
    Route::get('reports/{key}', [ReportController::class, 'show'])->name('reports.show');
    Route::post('tournaments/{tournament}/events', [EventController::class, 'store'])
        ->name('tournaments.events.store')->scopeBindings();
    Route::get('tournaments/{tournament}/events/{event}', [EventController::class, 'show'])
        ->name('tournaments.events.show')->scopeBindings();
    Route::patch('tournaments/{tournament}/events/{event}', [EventController::class, 'update'])
        ->name('tournaments.events.update')->scopeBindings();
    Route::delete('tournaments/{tournament}/events/{event}', [EventController::class, 'destroy'])
        ->name('tournaments.events.destroy')->scopeBindings();
    Route::post('tournaments/{tournament}/events/{event}/participants', [EventParticipantController::class, 'store'])
        ->name('tournaments.events.participants.store')->scopeBindings();
    Route::patch('tournaments/{tournament}/events/{event}/participants/{participation}', [EventParticipantController::class, 'update'])
        ->name('tournaments.events.participants.update')->scopeBindings();
    Route::delete('tournaments/{tournament}/events/{event}/participants/{participation}', [EventParticipantController::class, 'destroy'])
        ->name('tournaments.events.participants.destroy')->scopeBindings();
    Route::post('teams/{team}/members/backfill/preview', [TeamMemberController::class, 'previewBackfill'])->name('teams.members.backfill.preview');
    Route::post('teams/{team}/members/backfill', [TeamMemberController::class, 'backfill'])->name('teams.members.backfill');
    Route::post('teams/{team}/members', [TeamMemberController::class, 'store'])->name('teams.members.store');
    Route::delete('teams/{team}/members/bulk', [TeamMemberController::class, 'bulkDestroy'])->name('teams.members.bulkDestroy');
    Route::patch('teams/{team}/memberships/{teamMember}', [TeamMemberController::class, 'update'])->name('teams.members.update');
    Route::delete('teams/{team}/members/{member}', [TeamMemberController::class, 'destroy'])->name('teams.members.destroy');
    Route::post('teams/{team}/coaches', [TeamCoachController::class, 'store'])->name('teams.coaches.store');
    Route::delete('teams/{team}/coaches/bulk', [TeamCoachController::class, 'bulkDestroy'])->name('teams.coaches.bulkDestroy');
    Route::delete('teams/{team}/coaches/{coach}', [TeamCoachController::class, 'destroy'])->name('teams.coaches.destroy');
    Route::post('teams/{team}/incharge', [TeamInchargeController::class, 'store'])->name('teams.incharge.store');
    Route::patch('teams/{team}/incharge', [TeamInchargeController::class, 'update'])->name('teams.incharge.update');
    Route::delete('teams/{team}/incharge', [TeamInchargeController::class, 'destroy'])->name('teams.incharge.destroy');
    Route::post('teams/{team}/clone', TeamCloneController::class)->name('teams.clone');
    Route::patch('teams/{team}/session-status', [TeamSessionStatusController::class, 'close'])->name('teams.session-status.close');
    Route::patch('teams/{team}/session-status/activate', [TeamSessionStatusController::class, 'activate'])->name('teams.session-status.activate');
    Route::post('members/{member}/status', [MemberStatusController::class, 'store'])->name('members.status.store');
    Route::post('members/{member}/aliases', [MemberAliasController::class, 'store'])->name('members.aliases.store');
    Route::delete('members/{member}/aliases/{alias}', [MemberAliasController::class, 'destroy'])->name('members.aliases.destroy');
    Route::post('members/{member}/photo', [MemberPhotoController::class, 'store'])->name('members.photo.store');
    Route::delete('members/{member}/photo', [MemberPhotoController::class, 'destroy'])->name('members.photo.destroy');
    Route::post('members/{member}/special-achievements', [MemberSpecialAchievementController::class, 'store'])->name('members.special-achievements.store');
    Route::patch('members/{member}/special-achievements/{specialAchievement}', [MemberSpecialAchievementController::class, 'update'])->name('members.special-achievements.update');
    Route::delete('members/{member}/special-achievements/{specialAchievement}', [MemberSpecialAchievementController::class, 'destroy'])->name('members.special-achievements.destroy');
    Route::get('members/{member}/special-achievements/{specialAchievement}/order-document', [MemberSpecialAchievementController::class, 'orderDocument'])->name('members.special-achievements.order-document');
    Route::get('members/{member}/special-achievements/{specialAchievement}/order-document/preview', [MemberSpecialAchievementController::class, 'previewOrderDocument'])->name('members.special-achievements.order-document.preview');
    Route::post('members/{member}/achievements/resolve-and-store', [MemberAchievementContextController::class, 'store'])->name('members.achievements.resolve-and-store');
    Route::post('members/{member}/promotions', [MemberPromotionController::class, 'store'])->name('members.promotions.store');
    Route::patch('members/{member}/promotions/{promotion}', [MemberPromotionController::class, 'update'])->name('members.promotions.update');
    Route::delete('members/{member}/promotions/{promotion}', [MemberPromotionController::class, 'destroy'])->name('members.promotions.destroy');
    Route::get('members/{member}/audit-log', MemberAuditLogController::class)->name('members.audit-log.index');
    Route::post('achievement-benefits', [AchievementBenefitController::class, 'store'])->name('achievement-benefits.store');
    Route::patch('achievement-benefits/{benefit}', [AchievementBenefitController::class, 'update'])->name('achievement-benefits.update');
    Route::delete('achievement-benefits/{benefit}', [AchievementBenefitController::class, 'destroy'])->name('achievement-benefits.destroy');
    Route::get('participations/{participation}/media', [MediaFileController::class, 'index'])->name('participations.media.index');
    Route::post('participations/{participation}/media', [MediaFileController::class, 'store'])->name('participations.media.store');
    Route::delete('participations/{participation}/media/{mediaFile}', [MediaFileController::class, 'destroy'])->name('participations.media.destroy');
    Route::get('members/{member}/promotions/{promotion}/media', [MediaFileController::class, 'indexPromotion'])->name('members.promotions.media.index');
    Route::post('members/{member}/promotions/{promotion}/media', [MediaFileController::class, 'storePromotion'])->name('members.promotions.media.store');
    Route::delete('members/{member}/promotions/{promotion}/media/{mediaFile}', [MediaFileController::class, 'destroyPromotion'])->name('members.promotions.media.destroy');
});

require __DIR__.'/settings.php';
